import Footer from "@/components/Footer";
import "./globals.css";
import NavBar from "@/components/NavBar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Jenil Saija</title>
        <link rel="icon" href="/logo.png" />
      </head>
      <body>
        <NavBar/>
        <div className="h-fit">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
